import javax.swing.*;

public class CreateJobGUI {
    private JPanel createJobPanel;
    private JLabel formTitle;
    private JLabel jobIDLabel;
    private JLabel intJobIDLabel;
    private JLabel jobTitleLabel;
    private JTextField jobTitleText;
    private JLabel recruiterIDLabel;
    private JLabel intRecIDLabel;
    private JLabel employerLabel;
    private JLabel empNameLabel;
    private JLabel jobTypeLabel;
    private JComboBox jobTypeMenu;
    private JLabel salaryLabel;
    private JTextField salaryText;
    private JComboBox salaryMenu;
    private JLabel skillsLabel;
    private JComboBox comboBox1;
    private JList skillsList;
    private JButton addSkillButton;
    private JButton removeSkillButton;
    private JLabel keywordsLabel;
    private JComboBox keywordsMenu;
    private JList keywordsList;
    private JButton addKeywordsButton;
    private JButton removeKeywordsButton;
    private JLabel locationLabel;
    private JComboBox locationStateMenu;
    private JLabel postcodeLabel;
    private JTextField postcodeText;
    private JLabel descriptionLabel;
    private JFormattedTextField descriptionText;
    private JLabel categoryLabelPrimary;
    private JLabel categoryLabelSecondary;
    private JComboBox categoryMenuPrimary;
    private JComboBox categoryMenuSecondary;
    private JLabel hoursLabel;
    private JTextField hoursText;
    private JComboBox hoursMenu;
    private JLabel statusLabel;
    private JComboBox statusMenu;
    private JLabel statusMessageLabel;
}
