import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class LoginGUI {

    private JSS program;
    private String username;
    private char [] password;

    private JLabel loginTitle;
    public JPanel loginPanel;
    private JLabel loginUsername;
    private JTextField usernameField;
    private JPasswordField welcomeToJSSPasswordField;
    private JLabel loginPassword;
    private JButton loginButton;
    private JButton registerButton;
    private JLabel outputLabel;



    public LoginGUI(JSS program) {

        this.program = program;
        JFrame frame = new JFrame("LoginGUI");
        frame.setContentPane(this.loginPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String username = usernameField.getText();
                char[] password = welcomeToJSSPasswordField.getPassword();

                try
                {
                    program.login(username, password);
                }
                catch (Exception x)
                {
                    outputLabel.setText("System Error! Contact Admin with message: " + x.toString());
                    outputLabel.setVisible(true);
                    x.printStackTrace();
                }

                //Clear the password box
                clearPassword();
            }
        });

        registerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                try
                {
                    frame.dispose();
//                 TestGUI test = new TestGUI();
                   RegisterGUI register = new RegisterGUI(program);
                }
                catch (Exception x)
                {
                    outputLabel.setText("System Error contact Admin with message " + x.toString());
                    outputLabel.setVisible(true);
                    x.printStackTrace();
                }
            }
        });
    }

    // Method to clear the password box
    // Having trouble calling this from a static context at the moment...
    public void clearPassword() {
        welcomeToJSSPasswordField.setText("");
    }

    /*public static void main(String[] args) {
        JFrame frame = new JFrame("LoginGUI");
        frame.setContentPane(new LoginGUI().loginPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }*/

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginPanel = new JPanel();
        loginPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 3, new Insets(20, 300, 20, 300), -1, 5));
        loginPanel.setBackground(new Color(-4404254));
        loginPanel.setPreferredSize(new Dimension(1000, 667));
        loginTitle = new JLabel();
        loginTitle.setAlignmentX(0.0f);
        loginTitle.setBackground(new Color(-5494468));
        loginTitle.setEnabled(true);
        Font loginTitleFont = this.$$$getFont$$$("Cooper Black", Font.BOLD, 40, loginTitle.getFont());
        if (loginTitleFont != null) loginTitle.setFont(loginTitleFont);
        loginTitle.setForeground(new Color(-13220529));
        loginTitle.setText("Welcome to JSS!");
        loginTitle.setVerticalAlignment(0);
        loginPanel.add(loginTitle, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(358, 204), null, 4, false));
        loginUsername = new JLabel();
        Font loginUsernameFont = this.$$$getFont$$$("Lucida Sans Unicode", -1, 16, loginUsername.getFont());
        if (loginUsernameFont != null) loginUsername.setFont(loginUsernameFont);
        loginUsername.setForeground(new Color(-13220529));
        loginUsername.setText("Username");
        loginPanel.add(loginUsername, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        loginPassword = new JLabel();
        Font loginPasswordFont = this.$$$getFont$$$("Lucida Sans Unicode", -1, 16, loginPassword.getFont());
        if (loginPasswordFont != null) loginPassword.setFont(loginPasswordFont);
        loginPassword.setForeground(new Color(-13220529));
        loginPassword.setText("Password");
        loginPanel.add(loginPassword, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        welcomeToJSSPasswordField = new JPasswordField();
        Font welcomeToJSSPasswordFieldFont = this.$$$getFont$$$("Lucida Console", -1, 16, welcomeToJSSPasswordField.getFont());
        if (welcomeToJSSPasswordFieldFont != null) welcomeToJSSPasswordField.setFont(welcomeToJSSPasswordFieldFont);
        loginPanel.add(welcomeToJSSPasswordField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 2, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginButton = new JButton();
        loginButton.setActionCommand("");
        loginButton.setLabel("Sign In");
        loginButton.setText("Sign In");
        loginButton.setVerticalAlignment(0);
        loginPanel.add(loginButton, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, -1), null, 3, false));
        usernameField = new JTextField();
        Font usernameFieldFont = this.$$$getFont$$$("Lucida Console", -1, 16, usernameField.getFont());
        if (usernameFieldFont != null) usernameField.setFont(usernameFieldFont);
        usernameField.setForeground(new Color(-13220529));
        loginPanel.add(usernameField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, 20), null, 0, false));
        registerButton = new JButton();
        registerButton.setLabel("Sign Up");
        registerButton.setText("Sign Up");
        loginPanel.add(registerButton, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, -1), null, 0, false));
        outputLabel = new JLabel();
        Font outputLabelFont = this.$$$getFont$$$("Lucida Sans Unicode", -1, 12, outputLabel.getFont());
        if (outputLabelFont != null) outputLabel.setFont(outputLabelFont);
        outputLabel.setText("");
        outputLabel.setVisible(false);
        loginPanel.add(outputLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginUsername.setLabelFor(usernameField);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginPanel;
    }

}
